### ISSUE TITLE
User is not authorized to connect in GLPI

### ISSUE THREAD

**Issue by itmicus** [edgardmessias/glpi-singlesignon#1]
GLPI 9.4.3
Last version glpi-singlesignon

A have created Facebook provider
After try to login I have message
"User is not authorized to connect in GLPI"

I try add other provider Office 365 as generic.
And I have same error.

In GLPI config:
Automatically add users from an external authentication source - Yes

Can I create user in GLPI before use SSO? or user will be creating self

**Comment by edgardmessias** [comment]
The current version, you need create the user first.

**Comment by itmicus** [comment]
What is attribute User need?

С уважением
Павел Кузнецов
________________________________

**Comment by edgardmessias** [comment]
Look: inc/provider.class.php#L836
First try find by e-mail, after username

**Comment by itmicus** [comment]
ok, I did it - SSO with Office 365.

1. You need Office 365 subscription
Open https://portal.azure.com and sing-on with global administrator
Go to Azure Active Directory -> App registrations 
New registration, input Name and RedirectURI like 
> https://localhost/plugins/singlesignon/front/callback.php/provider/id_provider_Office365

id_provider_Office365 it is ID of SSO item, you can get it after step 3.
Go to Secrets and certificates, New client secret. Enter Name and get Secret

2. Plugin, in code inc/provider.class.php#L853
add 'mail'
> $email_fields = ['mail', 'email', 'e-mail', 'email-address'];

3. Create generic SSO:

> Name: Office 365
> Client ID: <Application (client) ID>
> Client Secret : <client secret>  
> Scope: https://graph.microsoft.com/user.read offline_access
> Authorize URL: <Endpoint Oauth 2.0 Authorize endpoint> 
> Access Token URL: <Endpoint Oauth 2.0 token endpoint> 
> Resource Owner Details URL https://graph.microsoft.com/v1.0/me

4. Create user with Email
5. Done!

**Comment by titansmc** [comment]
Hi, is it still the case that I need to create a user myself? I have configured keycloak
