### ISSUE TITLE
Plugin don't work

### ISSUE THREAD

**Issue by TxX8N8LN** [edgardmessias/glpi-singlesignon#10]
Hi Edgard,
i try your pluging, but nothing work.

I use GLPI 9.5.4. (I try your plugin version 1.3.1 and 1.2)

I create a provider with generic to my Keycloak.

But when i click on "Login with Keycloak, i'm redirected to GLPI connection white page, normaly it's provider interface connexion?

In this white page, any try do nothing. (no log too)

I have no log, no request was sent to my keycloak.

Thx for your return 

![GLPI_2](https://user-images.githubusercontent.com/59447936/113299231-f41eb880-92fc-11eb-8d79-b239bb665c36.png)
![GLPI_1](https://user-images.githubusercontent.com/59447936/113299233-f4b74f00-92fc-11eb-8c30-df10fffda779.png)

**Comment by edgardmessias** [comment]
Closed in favor of #26
