### ISSUE TITLE
AADSTS650056: Misconfigured application

### ISSUE THREAD

**Issue by caparozlucas** [edgardmessias/glpi-singlesignon#13]
AADSTS650056: Misconfigured application. This could be due to one of the following: the client has not listed any permissions for 'AAD Graph' in the requested permissions in the client's application registration. Or, the admin has not consented in the tenant. Or, check the application identifier in the request to ensure it matches the configured client application identifier. Or, check the certificate in the request to ensure it's valid. Please contact your admin to fix the configuration or consent on behalf of the tenant. Client app ID: 2f7f888c-3106-4599-a5fc-dcc39e7acde1.

Já olhei diversos LINKS e nada... consegue me ajudar edgar ?

SAML RESPONSE - LOGS

<samlp:Response ID="_059ec332-8406-485f-bb7f-231d25f82988" Version="2.0" IssueInstant="2021-06-17T13:51:10.637Z" Destination="https://suportehomologacao.inventcloud.com.br/" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"><Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">https://sts.windows.net/cba531a8-d084-4473-a98f-b0c212ab7b7e/</'><samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></samlp:Status><Assertion ID="_0cc73e4a-2dac-4016-b7af-d8a8bfd72500" IssueInstant="2021-06-17T13:51:10.632Z" Version="2.0" xmlns="urn:oasis:names:tc:SAML:2.0:assertion"><Issuer>https://sts.windows.net/cba531a8-d084-4473-a98f-b0c212ab7b7e/</Issuer><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><Reference URI="#_0cc73e4a-2dac-4016-b7af-d8a8bfd72500"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><DigestValue>uachxpOq7/t3pyeFn7y6gf/KcL1431DMPykE5xoEljo=</DigestValue></Reference></SignedInfo><SignatureValue>DL1DwiAGBOFNKSFx9Ar8I7hg69sRj5W1rT0TzUcI9k8pwWR6O13wTsfYPXfJ9zeeExM+EjuGK9F1pxJ7axAF4Vx1zlh2M32b6SbyffGHphjWna7j7zLWsdamjtSvtitA9GDZuymYjU44tlqsnbzMiVVBztz3bEPSXGwo/8+QGbO1sBypPvVhifMkPmroprOnBvRT6469UZD72J+F/lIC4bQ9cpw8uLZbyCGqV+JsTGK0cSET+aS4rH0PlAt4CzO7GXS/Xgv3UyOjVvbz5Vp/5RVU5g1MNJmOuSc0M4CUa5VN0lB/kT7beodTm1/geL1z1UcsULAFFx68+CjdHtwM3w==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIC8DCCAdigAwIBAgIQXAbJy9z1pqtJrRwxLIbR1DANBgkqhkiG9w0BAQsFADA0MTIwMAYDVQQDEylNaWNyb3NvZnQgQXp1cmUgRmVkZXJhdGVkIFNTTyBDZXJ0aWZpY2F0ZTAeFw0yMTA1MTcxOTU1NDdaFw0yNDA1MTcxOTU1NDdaMDQxMjAwBgNVBAMTKU1pY3Jvc29mdCBBenVyZSBGZWRlcmF0ZWQgU1NPIENlcnRpZmljYXRlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmaE4SzpLK15YwFRR2/CAyAu2azwBvvoPcQoB/eikhZxBCGKlHPEx+GjjbzcnVEl6OsR4tIOYOL9owi/afuqQ5rx091nd6WFQzyHtWjtEa248EG+XT4rkROv8PmqpJeNQH85rX4OR/8bCcecwd4rCVdkX536gHJZl57k35omBiGZvuGBDIqpKkcomcm7HfR1dkHniOGqsgVBQ8nacd5LFAU615hriE2RIFQqfAH+Tn3rrf3vY5BFvrwzi/o8n9AAXdTL8+m4eOHv4n4UlBzlscHte/C5Fp826n2o2tz4Rn2lR+jn6e+wy9X6Fydcl5lfTNl8a/RPkETQ1Y+nQFMOARQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQB+RV9vVxT0NGh8f/TB7oAnvy42SLBYDIwORx7wXNi4QtGZpeG+tcP0KtzKKR3yHoH3wFisYuPQfvpkyFhITgAKyglFEjDtGZYttSOB/K9in9pAdgDiDNbd4kZo2HgsR3zjmGrBLe1bkIG02od54RrRs4lm96PxM27JWNRaWJqf6mQ7va1f85n0QXgN+S1K90XxhbUQGIKTywbVGQoI2ZtmRG7vFrs3++KGfPLopix6/log8FWwayHmq35FT8teNb5YJ2fG4qwSxLZK87rpkFcvEV1s/tdSHNIs4wFGOmhz+m+QuSs+D68fVSX8EZm3hvFROE1pAgmXLgpa3sVT/meF</X509Certificate></X509Data></KeyInfo></Signature><Subject><NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">lucas.caparoz@inventcloud.com.br</NameID><SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><SubjectConfirmationData NotOnOrAfter="2021-06-17T14:51:10.457Z" Recipient="https://suportehomologacao.inventcloud.com.br/"/></SubjectConfirmation></Subject><Conditions NotBefore="2021-06-17T13:46:10.457Z" NotOnOrAfter="2021-06-17T14:51:10.457Z"><AudienceRestriction><Audience>https://suportehomologacao.inventcloud.com.br/saml2</Audience></AudienceRestriction></Conditions><AttributeStatement><Attribute Name="http://schemas.microsoft.com/identity/claims/tenantid"><AttributeValue>cba531a8-d084-4473-a98f-b0c212ab7b7e</AttributeValue></Attribute><Attribute Name="http://schemas.microsoft.com/identity/claims/objectidentifier"><AttributeValue>f2105918-bcb8-4ba9-9681-26d3ddda1e49</AttributeValue></Attribute><Attribute Name="http://schemas.microsoft.com/identity/claims/displayname"><AttributeValue>Lucas Caparoz</AttributeValue></Attribute><Attribute Name="http://schemas.microsoft.com/identity/claims/identityprovider"><AttributeValue>https://sts.windows.net/cba531a8-d084-4473-a98f-b0c212ab7b7e/</AttributeValue></Attribute><Attribute Name="http://schemas.microsoft.com/claims/authnmethodsreferences"><AttributeValue>http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/password</AttributeValue><AttributeValue>http://schemas.microsoft.com/claims/multipleauthn</AttributeValue></Attribute><Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname"><AttributeValue>Lucas</AttributeValue></Attribute><Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname"><AttributeValue>Caparoz</AttributeValue></Attribute><Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"><AttributeValue>lucas.caparoz@inventcloud.com.br</AttributeValue></Attribute><Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"><AttributeValue>lucas.caparoz@inventcloud.com.br</AttributeValue></Attribute></AttributeStatement><AuthnStatement AuthnInstant="2021-06-17T13:47:53.340Z" SessionIndex="_0cc73e4a-2dac-4016-b7af-d8a8bfd72500"><AuthnContext><AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</AuthnContextClassRef></AuthnContext></AuthnStatement></Assertion></samlp:Response>

**Comment by mrgeppetto** [comment]
I believe this plugin is Oauth/openID, that is for SAML. Check out [SAML Plugin](https://github.com/derricksmith/phpsaml)
