### ISSUE TITLE
Azure AD Permissão

### ISSUE THREAD

**Issue by fellipedemoraes** [edgardmessias/glpi-singlesignon#14]
Boa tarde,
Parabéns pelo trabalho e plugin.

Aqui deu certo até a parte Azure, no GLPI como eu libero pra acessar?

![image](https://user-images.githubusercontent.com/16623373/124313307-14058880-db47-11eb-932a-994ab434397b.png)

Obrigado,

**Comment by edgardmessias** [comment]
Existem duas formas, vincular no cadastro do usuário, ou ter mesmo ID ou e-mail

**Comment by fellipedemoraes** [comment]
Como faço isto? Não achei nada relacionado no cadastro do usuário e o mesmo id e e-mail mostrou a mesma mensagem de erro.

**Comment by randallmoraes** [comment]
> Como faço isto? Não achei nada relacionado no cadastro do usuário e o mesmo id e e-mail mostrou a mesma mensagem de erro.



In the Resource Owner Details URL put https://graph.microsoft.com/v1.0/me for request the email of the user logged

**Comment by edgardmessias** [comment]
Could you update to latest release and run "Test" from config page?

https://github.com/edgardmessias/glpi-singlesignon/releases/tag/v1.3.3

**Comment by edgardmessias** [comment]
Closed in favor of #26
