### ISSUE TITLE
Can't authenticate user Azure ad

### ISSUE THREAD

**Issue by ibenamar** [edgardmessias/glpi-singlesignon#16]
Users are unable to authenticate if their account haven't been previously linked on the user preferences
missing something ?

**Comment by edgardmessias** [comment]
You must create an user with the same e-mail or username

**Comment by edgardmessias** [comment]
Closed in favor of #26

**Comment by nykroy** [comment]
If the user does not have a license in azure I have problems logging in. is a license necessary?
