### ISSUE TITLE
 Provider not defined.

### ISSUE THREAD

**Issue by alyfilipe** [edgardmessias/glpi-singlesignon#22]
Não consegui sucesso usando o google:
Adicionei o client ID e a senha. No google coloquei a url de callback que o plugin me deu.
Ao testar a URL de callback, recebo: Provider not defined.

O que eu perdi?

Abraço,

**Comment by alyfilipe** [comment]
Ao efetuar logoff/logon, erro em anexo
![Captura de tela de 2022-01-22 00-55-00](https://user-images.githubusercontent.com/38772215/150623807-9a0c9319-ddba-44fb-a768-b5f635d30cfc.png)
.

**Comment by edgardmessias** [comment]
Could you update to latest release and run "Test" from config page?

https://github.com/edgardmessias/glpi-singlesignon/releases/tag/v1.3.3

**Comment by edgardmessias** [comment]
Closed in favor of #26
