### ISSUE TITLE
User is not authorized to connect in GLPI

### ISSUE THREAD

**Issue by champakakumara** [edgardmessias/glpi-singlesignon#27]
![image](https://user-images.githubusercontent.com/104112313/169242984-805cb7ef-76fa-47c5-982d-be5ae252c930.png)

error with google ,Any idea?

**Comment by oswalvas** [comment]
I have the same problem with google

**Comment by edgardmessias** [comment]
Could you update to latest release and run "Test" from config page?

https://github.com/edgardmessias/glpi-singlesignon/releases/tag/v1.3.3

**Comment by oswalvas** [comment]
Thank you for your reply.
I have a problem when I try to reinstall the plugins.
![image](https://user-images.githubusercontent.com/108331767/176428976-b5af6081-9f32-4602-8720-8f41a4a6e36c.png)

But no matter what I have backup where I restore to a previous version.

I have tried with the new version and I get the following error.
![image](https://user-images.githubusercontent.com/108331767/176431299-e555d806-f176-4ba3-b812-d628baf1584f.png)

Do you know how I can fix it?

**Comment by champakakumara** [comment]
follow this
https://github.com/edgardmessias/glpi-singlesignon/issues/26

in file provider.class.php
change in line 909 and 956:
'redirect_uri' => $this->getCurrentURL(),
to
'redirect_uri' => 'https://your-site-name/plugins/singlesignon/front/callback.php/provider/',

and

in file callback.php in line 12

$provider_id = 1; //PluginSinglesignonToolbox::getCallbackParameters('provider');

**Comment by champakakumara** [comment]
> Thank you for your reply. I have a problem when I try to reinstall the plugins. ![image](https://user-images.githubusercontent.com/108331767/176428976-b5af6081-9f32-4602-8720-8f41a4a6e36c.png)
> 
> But no matter what I have backup where I restore to a previous version.
> 
> I have tried with the new version and I get the following error. ![image](https://user-images.githubusercontent.com/108331767/176431299-e555d806-f176-4ba3-b812-d628baf1584f.png)
> 
> Do you know how I can fix it?

follow this
https://github.com/edgardmessias/glpi-singlesignon/issues/26

in file provider.class.php
change in line 909 and 956:
'redirect_uri' => $this->getCurrentURL(),
to
'redirect_uri' => 'https://your-site-name/plugins/singlesignon/front/callback.php/provider/',

and

in file callback.php in line 12

$provider_id = 1; //PluginSinglesignonToolbox::getCallbackParameters('provider');

**Comment by champakakumara** [comment]
Work Google SSO on GLPI 10 with glpi-singlesignon v1.3.3

**Comment by champakakumara** [comment]
configure AthorizedDomain in singlesighon configuration
Ex;-
AthorizedDomains - ABC.com

**Comment by chrisBer31** [comment]
Same issue with oauth2 provide with wso2

**Comment by edgardmessias** [comment]
Closed in favor of #26
