### ISSUE TITLE
GLPI 10 

### ISSUE THREAD

**Issue by LuizRicarte** [edgardmessias/glpi-singlesignon#28]
Vai desenvolver esse Plugin para o GLPI 10?

**Comment by edgardmessias** [comment]
Não estou tendo muito tempo de mexer com GLPI, mas se alguém quiser ajudar, eu faço a revisão e merge da solicitação

**Comment by RaulPastorClemente** [comment]
I can confirm that v1.3.1 is working for me in GLPI v10. I'm using Google as SSO provider.
