### ISSUE TITLE
Erro 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by LuizRicarte** [edgardmessias/glpi-singlesignon#29]
Estou recebendo o Erro 400: redirect_uri_mismatch, com o login com o google

**Comment by edgardmessias** [comment]
Could you update to latest release and run "Test" from config page?

https://github.com/edgardmessias/glpi-singlesignon/releases/tag/v1.3.3

**Comment by edgardmessias** [comment]
Closed in favor of #26
