### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by Cial39** [edgardmessias/glpi-singlesignon#31]
the single sign on test is ok but error "PHP Notice: Array to string conversion in C:\inetpub\wwwroot\glpi\plugins\singlesignon\inc\toolbox.class.php on line 17" after disconnection. Can you help me
![Capture d’écran 2022-06-29 204932](https://user-images.githubusercontent.com/108429029/176515283-87c52af4-4157-441d-ba70-340578cdc4e0.png)
.

**Comment by edgardmessias** [comment]
Closed in favor of #26
