### ISSUE TITLE
Azure providers.json issue

### ISSUE THREAD

**Issue by 157Frog** [edgardmessias/glpi-singlesignon#34]
Hi, 
I was trying to use this with azure with Azure App as single tenancy authentication.  However I get the following azure error when testing:

"is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant."

Looking in your providers.json file I see you have this hard coded:

        "url_authorize": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
        "url_access_token": "https://login.microsoftonline.com/common/oauth2/v2.0/token",

It seems this needs to be changed to: "https://login.microsoftonline.com/ TENANTNAME or ID"

I'm looking to manually change the /common to my tennant ID to get this working but came across other issue uninstalling (logged as separate issue) but is there any option to add this tennant ID in the config interface? 

Thanks

**Comment by Cial39** [comment]
hi

https://forum.glpi-project.org/viewtopic.php?id=169902
