### ISSUE TITLE
User is not authorized to connect in GLPI

### ISSUE THREAD

**Issue by chrisBer31** [edgardmessias/glpi-singlesignon#35]
I have setup the plugin version 1.3.3 with glpi 9.5.6

I have the same issue : user not authorized after oauth2 session login

Plugin config :
SSO Type : Generic
Client ID : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 
Client Secret : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Scope : openid
Authorize URL : https://identity.dev.com/oauth2/authorize
Access Token URL : https://identity.dev.com/oauth2/token
Resource Owner Details URL : https://identity.dev.com/oauth2/userinfo

What are the claims need to configure oauth2 service provider ?

**Comment by r1card0sl** [comment]
Estou com o mesmo problema.

**Comment by edgardmessias** [comment]
Closed in favor of #26
