### ISSUE TITLE
Code is not licenced

### ISSUE THREAD

**Issue by Bert-Proesmans** [edgardmessias/glpi-singlesignon#36]
Hi Edgard,

I've recently started exploring GLPI in our organization. This repository seems like a good starting point to enable SSO on top of GLPI. I'd like to fork and contribute back, but the lack of licence prohibits me.

Is there a possibility to licence the code, or explicitly allow me or my company to modify the code in this repository?

**Comment by edgardmessias** [comment]
Hi @Bert-Proesmans , I will update to put it
