### ISSUE TITLE
Azure: Can NOT Login

### ISSUE THREAD

**Issue by acremonezi** [edgardmessias/glpi-singlesignon#37]
Issue:  **Can NOT login using Microsoft Azure**

**GLPI Version:** 10.0.1
**Azure App Supported Account types:** Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts.
**Plugin Version:** Current one ([v1.3.3](https://github.com/edgardmessias/glpi-singlesignon/releases/tag/v1.3.3)) just cloned the main branch.

**How to reproduce the issue:** The issue was discovered by login with an user with login XXXX and email address XXXX@hotmail.com. The output when trying to login is following.

**Extra Info 1:** The "Test Button" on SSO Provider screen works well showing the API return when add the approval call back return URL as /plugins/singlesignon/front/callback.php/provider/2/teste/1

**Extra Info 2:** I setup Google Login and it works perfectly.

**Details:**

`Notice: Undefined variable: authorizedDomains in /var/www/html/glpi/plugins/singlesignon/inc/provider.class.php on line 1122`

`Warning: Invalid argument supplied for foreach() in /var/www/html/glpi/plugins/singlesignon/inc/provider.class.php on line 1122`

![image](https://user-images.githubusercontent.com/32877060/178859928-2fc7d0c0-6b50-45df-b30b-a4f914fd13bf.png)

Many Thanks in advanced due to any help and guidance.

**Comment by edgardmessias** [comment]
Closed in favor of #26
