### ISSUE TITLE
OKTA Support

### ISSUE THREAD

**Issue by SmoZy92** [edgardmessias/glpi-singlesignon#45]
Hello,

First of all, thank you for your contribution and the plugin you created.

I would like to know if you planned to add a support of OKTA SSO in a near futur or not.

Best regards

**Comment by virtazp** [comment]
Hi, I don't know Okta. Have you tried getting OKTA SSO to work with the generic type?
To my knowledge, no development is planned.

**Comment by SmoZy92** [comment]
Hello, 

OKTA is currently the market leader for Identity and Access Management + SSO

Since the SSO used by the plugin is OpenID Connect, it is compatible with OKTA !

I successfully managed to setup SSO for OKTA using the generic type.


Thank you @virtazp
