### ISSUE TITLE
Classe "User" Missing ?

### ISSUE THREAD

**Issue by franckdurand0334** [edgardmessias/glpi-singlesignon#7]
Thanks for your great job  Edgard

PHP Fatal error:  Uncaught Error: Call to undefined method User::getById() in ....

   public function linkUser($user_id) {
      /** @var User */
      $user = User::getById($user_id);
      if (!$user) {
         return;

Regards Franck

**Comment by edgardmessias** [comment]
Hello @franckdurand0334 , what is your GLPI version?

**Comment by franckdurand0334** [comment]
Hi,

i use 9.4.5 on synology

I try with plugin 1.2  -> it s ok

Thanks
Franck

________________________________
De : Edgard Lorraine Messias <notifications@github.com>
Envoyé : vendredi 5 mars 2021 15:09
À : edgardmessias/glpi-singlesignon <glpi-singlesignon@noreply.github.com>
Cc : franckdurand0334 <franck.durand@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [edgardmessias/glpi-singlesignon] Classe "User" Missing ? (#7)


Hello @franckdurand0334<https://github.com/franckdurand0334> , what is your GLPI version?

**Comment by edgardmessias** [comment]
@franckdurand0334 , fixed issue
