### ISSUE TITLE
Warning (2): Trying to access array offset on a value of type int in toolbox.class.php

### ISSUE THREAD

**Issue by sina-4** [edgardmessias/glpi-singlesignon#76]
I'm using Singlesignon with debug mode active in GLPI, and it's functioning correctly. However, I've been encountering a significant number of warnings since I started using the Singlesignon plugin. I've noticed one specific warning on the plugin page that reads: 'PHP Warning (2): Trying to access array offset on a value of type int in /var/www/html/glpi10/plugins/singlesignon/inc/toolbox.class.php at line 17.' Could someone please assist me in resolving this issue?

**Comment by tomamplius** [comment]
I have fix with add ['id']


![image](https://github.com/edgardmessias/glpi-singlesignon/assets/6951820/b5587a88-307e-4c66-896b-15d9f5fbcaf1)

**Comment by tomamplius** [comment]
i have push https://github.com/edgardmessias/glpi-singlesignon/pull/77

**Comment by tomamplius** [comment]
duplicate with #75
