### ISSUE TITLE
Error 500 after login

### ISSUE THREAD

**Issue by jcmluquez** [edgardmessias/glpi-singlesignon#8]
Hi, im trying this excelent plugin on test enviroment, but Im getting 500 error after succefully login.
In apache log I can see this:
PHP Fatal error:  Uncaught Error: Call to undefined method User::getById() in /var/www/html/glpi-9.4/plugins/singlesignon/inc/provider.class.php:1116\nStack trace:\n#0 /var/www/html/glpi-9.4/plugins/singlesignon/front/callback.php(53): PluginSinglesignonProvider->linkUser('838')\n#1 {main}\n  thrown in /var/www/html/glpi-9.4/plugins/singlesignon/inc/provider.class.php on line 1116

Then, If I reload the page, Im already logged in. Im attaching the plugin configuration.
Many thanks in advance!
![Captura de pantalla de 2021-03-17 08-50-25](https://user-images.githubusercontent.com/10264358/111463274-2aa1e400-86fe-11eb-9c7f-346c15feecc7.png)

**Comment by edgardmessias** [comment]
@jcmluquez, fixed issue
