### ISSUE TITLE
 PHP Deprecated function (8192): str_replace(): 

### ISSUE THREAD

**Issue by leoinfra** [edgardmessias/glpi-singlesignon#88]
I set up authentication and it works wonderfully with Google.

It just didn't work to add an image.
I tried png, giff, sgv, jpg, ico. different sizes and it doesn't work.

In debug mode, these errors appear, but I don't know how to fix them.

Congratulations on the work.

PHP Deprecated function (8192): str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /var/www/glpi10/glpi/plugins/singlesignon/inc/provider.class.php at line 871

PHP Deprecated function (8192): hash_hmac(): Passing null to parameter #2 ($data) of type string is deprecated in /var/www/glpi10/glpi/plugins/singlesignon/inc/provider.class.php at line 872

**Comment by invisiblemarcel** [comment]
@leoinfra Adding a picture didn't work for me for generic as well. But I could figure out the problems and fixed them. See my pull request #89.
