### ISSUE TITLE
Error redirect_uri_missmatch

### ISSUE THREAD

**Issue by jcmluquez** [edgardmessias/glpi-singlesignon#9]
Hi Edgard.
First of all, many thanks for the previous reply in another issue.

Now, I want to know if there is somthing I'm missing in the configuration. The problem I have is when I point to a direct access to a tiket like this http://glpiprueba.unrn.edu.ar/front/ticket.form.php?id=34 I get the error in the attached screenshot when clicking on the login button.
I already verify in the google console for the allowed URI redirection and everything seems to be ok.
![Captura de pantalla de 2021-03-22 13-10-53](https://user-images.githubusercontent.com/10264358/112022186-cc676d80-8b10-11eb-90b3-452788480ded.png)
![Captura de pantalla de 2021-03-22 13-17-50](https://user-images.githubusercontent.com/10264358/112022456-17818080-8b11-11eb-973d-769be38cacb1.png)

Can you help me please?
Many thanks in advance!
Regards,

**Comment by edgardmessias** [comment]
It is a problem with google authenticator, that is impossible to use a dynamic URL to auth.

I am working on an alternative to solve it

**Comment by jcmluquez** [comment]
Great!
Many thanks!
